on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  
  jobs:
    build:
      run-on: ubuntu-latest
      steps: 
        uses: actions/checkout@v2
        run: Executing actions, online scripts
        name: Project actions in v2


  